### ISSUE TITLE
Wrong exposed ports (typo ?)

### ISSUE THREAD

**Issue by gbouthenot** [spritsail/deluge#2]
Hello.
In README.md, you expose the following ports:
```
-p 51360:51360/udp
```

But in the Dockerfile, the ports to be exposed are:
```
EXPOSE 53160
EXPOSE 53160/udp
```

The tcp port is not exposed in the the example, and the udp port is wrong. Is this a typo ?

Also what is the use for the ports 53160 Is this the port you setup to to p2p trafik ?
And port 58846 is the deaemon port. Why do you expose it ? I think that exposing the webui port is enough.

Thank for your work by the way ! Your docker image is useful !

**Comment by ldexterldesign** [comment]
BUMP

**Comment by frebib** [comment]
Sorry for the lack of response
The `EXPOSE` statements in the Dockerfile are merely a suggestion. You're right though, there probably shouldn't be a discrepancy. I'm tempted to remove those port definitions because they're specific to this example anyway, and the daemon port can vary by user.
You're right, in most cases just exposing the web port is enough. If you want to be able to connect to the daemon with another client (such as the gtk client) you'll need to expose your daemon port too.
