### ISSUE TITLE
More Detailed Instructions

### ISSUE THREAD

**Issue by Chronigan** [spritsail/deluge#3]
Hello, I am new to docker and while I have been able to install and start the container, I can't figure out how to interact with it over my network. I was hoping you might be willing to break down the commands in the line you give to create the container and anything that needs to be done once the container has been created so we can interact with deluge over the network. Thanks for your help!

**Comment by frebib** [comment]
It's been a long time since you posted this. Sorry for not getting back to you originally. If you still need any help, feel free to re-open the issue. If you start the container with the provided `docker run ..` command from the README, then you should be able to navigate to the Deluge web ui in your browser with http://\<host>\:8112/ or http://localhost:8112 if you're running it on the local computer. Generally though, this kind of a question can be answered by playing around with Docker and understanding how it works. Here isa a good place to get started with that: https://docs.docker.com/engine/reference/run/
